### ISSUE TITLE
[FEAT] 공통 헤더 구현

### ISSUE THREAD

**Issue by cjy3458** [cau-likelion-org/kiwi-client#2]
## 📌 Issue 내용
***
- 공통 헤더 구현

## 📝 TO DO
***
- [ 공통 헤더 구현 완료 ]

## 💌 비고
***
-

**Comment by rbgksqkr** [comment]
Assignees 에는 이슈 담당하는 개발자만 하셔도 됩니당

**Comment by cjy3458** [comment]
옹 확인했습니다
