### ISSUE TITLE
[DESIGN] 랜딩 화면 크기 비율 문제 해결

### ISSUE THREAD

**Issue by cjy3458** [cau-likelion-org/kiwi-client#77]
## 📌 Issue 내용
***
- 작은 노트북에서 화면이 작아져서 요소와 상단바가 겹치는 상황 발생

## 📝 TO DO
***
- [ ] 랜딩 노트북 화면에 따른 문제 해결

## 💌 비고
***
-

**Comment by gominzip** [comment]
해결완료
